### ISSUE TITLE
Zuora.configure With :log => true Raises NoMethodError

### ISSUE THREAD

**Issue by sshaw** [zuorasc/zuora#32]
Using [the example from the README](https://github.com/zuorasc/zuora/blob/c2fe7aee7dd45e9385b926f6402e7160d4f95f02/README.md#getting-started) causes the following exception:

```
~/code/ruby/zoura-test >ruby run.rb
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /Users/skyes/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54)
/Users/skyes/.rvm/gems/ruby-2.2.5/gems/savon-2.3.3/lib/savon/request_logger.rb:29:in `log_request': undefined method `info' for nil:NilClass (NoMethodError)
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/savon-2.3.3/lib/savon/request_logger.rb:11:in `log'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/savon-2.3.3/lib/savon/operation.rb:86:in `call_with_logging'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/savon-2.3.3/lib/savon/operation.rb:51:in `call'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/savon-2.3.3/lib/savon/client.rb:36:in `call'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/zuora-1.0.0/lib/zuora/api.rb:105:in `authenticate!'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/zuora-1.0.0/lib/zuora/api.rb:85:in `request'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/zuora-1.0.0/lib/zuora/soap_connector.rb:11:in `query'
	from /Users/skyes/.rvm/gems/ruby-2.2.5/gems/zuora-1.0.0/lib/zuora/objects/base.rb:82:in `all'
	from run.rb:10:in `<main>'
```

**Comment by sshaw** [comment]
This is because we're telling Savon to log but [a `nil` `:logger` option being passed in](https://github.com/zuorasc/zuora/blob/c2fe7aee7dd45e9385b926f6402e7160d4f95f02/lib/zuora/api.rb#L122).
